[build]
  publish = "dist"
  command = "ls -la && cat package.json && npm install --include=dev && ls node_modules && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Headers for iframe embedding
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *;"
    Access-Control-Allow-Origin = "*"